In [1]:
import re
import pandas as pd
from IPython.display import display
from langdetect import detect, DetectorFactory
from langdetect.lang_detect_exception import LangDetectException

In [2]:
file_path = 'dataset_twitter1.csv'

# Membaca dataset
df = pd.read_csv(file_path)

CASE FOLDING

In [3]:
sampel_indeks = [176, 195, 815, 1140, 2615]
sebelum_tahap1 = df.loc[sampel_indeks, 'full_text']

In [4]:
df['clean_text'] = df['full_text'].astype(str).str.lower()

In [5]:
sesudah_tahap1 = df.loc[sampel_indeks, 'clean_text']

In [6]:
tabel_perbandingan_tahap1 = pd.DataFrame({
    'Sebelum': sebelum_tahap1,
    'Sesudah': sesudah_tahap1
})

In [7]:
print("CASE FOLDING")
pd.set_option('display.max_colwidth', None)
display(tabel_perbandingan_tahap1)

CASE FOLDING

,Sebelum,Sesudah
176,"@tekarok007 @tempodotco @bengkeldodo @ferrykoto @Heraloebss Faktanya apa ada anggota DPR yang usul jd ibu kota provinsi ? You cari tau , jgn cuma Saras soros . 😂","@tekarok007 @tempodotco @bengkeldodo @ferrykoto @heraloebss faktanya apa ada anggota dpr yang usul jd ibu kota provinsi ? you cari tau , jgn cuma saras soros . 😂"
195,@kompascom Sebenarnya buat siapa kepentingan mega Proyek IKN ini ?? Belum tentu Prabowo dan kabinetnya mau ngantor disana.,@kompascom sebenarnya buat siapa kepentingan mega proyek ikn ini ?? belum tentu prabowo dan kabinetnya mau ngantor disana.
815,@Ombahku Yg paling bener cuma pak ps di sini . Parah nih pak Mul,@ombahku yg paling bener cuma pak ps di sini . parah nih pak mul
1140,@tempodotco STOP UKN PROJECT MUBAZIR 🤔,@tempodotco stop ukn project mubazir 🤔
2615,@ganjarpranowo Tobat selama 10 tahun merasakan d pimpin oleh partai banteng segalax serba susah sekarang saatx perubahan https://t.co/98lUcAtLwL,@ganjarpranowo tobat selama 10 tahun merasakan d pimpin oleh partai banteng segalax serba susah sekarang saatx perubahan https://t.co/98lucatlwl

URL/Link

In [8]:
sebelum_tahap2 = df.loc[sampel_indeks, 'clean_text'].copy()

In [9]:
df['clean_text'] = df['clean_text'].apply(lambda x: re.sub(r'http\S+|www\S+|https\S+', '', str(x), flags=re.MULTILINE))

In [10]:
sesudah_tahap2 = df.loc[sampel_indeks, 'clean_text'].copy()

In [11]:
tabel_perbandingan_tahap2 = pd.DataFrame({
    'Sebelum': sebelum_tahap2,
    'Sesudah': sesudah_tahap2
})

In [12]:
print("PENGHAPUSAN URL")
pd.set_option('display.max_colwidth', None)
display(tabel_perbandingan_tahap2)

PENGHAPUSAN URL

,Sebelum,Sesudah
176,"@tekarok007 @tempodotco @bengkeldodo @ferrykoto @heraloebss faktanya apa ada anggota dpr yang usul jd ibu kota provinsi ? you cari tau , jgn cuma saras soros . 😂","@tekarok007 @tempodotco @bengkeldodo @ferrykoto @heraloebss faktanya apa ada anggota dpr yang usul jd ibu kota provinsi ? you cari tau , jgn cuma saras soros . 😂"
195,@kompascom sebenarnya buat siapa kepentingan mega proyek ikn ini ?? belum tentu prabowo dan kabinetnya mau ngantor disana.,@kompascom sebenarnya buat siapa kepentingan mega proyek ikn ini ?? belum tentu prabowo dan kabinetnya mau ngantor disana.
815,@ombahku yg paling bener cuma pak ps di sini . parah nih pak mul,@ombahku yg paling bener cuma pak ps di sini . parah nih pak mul
1140,@tempodotco stop ukn project mubazir 🤔,@tempodotco stop ukn project mubazir 🤔
2615,@ganjarpranowo tobat selama 10 tahun merasakan d pimpin oleh partai banteng segalax serba susah sekarang saatx perubahan https://t.co/98lucatlwl,@ganjarpranowo tobat selama 10 tahun merasakan d pimpin oleh partai banteng segalax serba susah sekarang saatx perubahan

Pembersihan Teks

In [13]:
sebelum_tahap3 = df.loc[sampel_indeks, 'clean_text'].copy()

In [14]:
def clean_tahap3(text):
    text = str(text)
    # Menghapus mention (@username)
    text = re.sub(r'\@\w+', '', text)
    # Menghapus simbol hashtag (#)
    text = re.sub(r'#', '', text)
    # Menghapus semua karakter selain huruf abjad (a-z) dan spasi
    # (Ini otomatis akan menghapus emoji, tanda baca, dan angka)
    text = re.sub(r'[^a-z\s]', ' ', text)
    # Menghapus spasi ganda atau berlebih dan merapikan ujung teks
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [15]:
df['clean_text'] = df['clean_text'].apply(clean_tahap3)

In [16]:
sesudah_tahap3 = df.loc[sampel_indeks, 'clean_text'].copy()

In [17]:
tabel_perbandingan_tahap3 = pd.DataFrame({
    'Sebelum': sebelum_tahap3,
    'Sesudah': sesudah_tahap3
})

In [18]:
print("Penghapusan emoji, mention, dan karakter")
pd.set_option('display.max_colwidth', None)
display(tabel_perbandingan_tahap3)

Penghapusan emoji, mention, dan karakter

,Sebelum,Sesudah
176,"@tekarok007 @tempodotco @bengkeldodo @ferrykoto @heraloebss faktanya apa ada anggota dpr yang usul jd ibu kota provinsi ? you cari tau , jgn cuma saras soros . 😂",faktanya apa ada anggota dpr yang usul jd ibu kota provinsi you cari tau jgn cuma saras soros
195,@kompascom sebenarnya buat siapa kepentingan mega proyek ikn ini ?? belum tentu prabowo dan kabinetnya mau ngantor disana.,sebenarnya buat siapa kepentingan mega proyek ikn ini belum tentu prabowo dan kabinetnya mau ngantor disana
815,@ombahku yg paling bener cuma pak ps di sini . parah nih pak mul,yg paling bener cuma pak ps di sini parah nih pak mul
1140,@tempodotco stop ukn project mubazir 🤔,stop ukn project mubazir
2615,@ganjarpranowo tobat selama 10 tahun merasakan d pimpin oleh partai banteng segalax serba susah sekarang saatx perubahan,tobat selama tahun merasakan d pimpin oleh partai banteng segalax serba susah sekarang saatx perubahan

NORMALISASI TEKS

In [19]:
sebelum_tahap4 = df.loc[sampel_indeks, 'clean_text'].copy()

In [20]:
url_kamus = 'https://raw.githubusercontent.com/nasalsabila/kamus-alay/master/colloquial-indonesian-lexicon.csv'

In [21]:
df_kamus = pd.read_csv(url_kamus)

In [22]:
slang_dict_publik = dict(zip(df_kamus['slang'], df_kamus['formal']))

In [ ]:
kamus_kustom = {
    'amp': 'dan', 
    'kalo': 'kalau', 
    'bgt': 'banget', 
    'bngt': 'banget',
    'siiiikkkkkkkk': 'sih', 
    'mlarat': 'melarat', 
    'jijiq': 'jijik',
    'wis wayahe': 'sudah waktunya', 
    'saatx': 'saat', 
    'bangettt': 'banget',
    'kebalikaaaannn': 'kebalikan',
    'bpk': 'bapak',
    'bangkruuut': 'bangkrut',
    'buzzerp': 'buzzer',
    'benaran': 'beneran',
    'gelo': 'gila',
    'Kagok': 'tanggung',
    'puyeng': 'pusing',
    'ink': 'ini',
    'dibuvarkan': 'dibubarkan',
    'insfrastruktur': 'infrastruktur',
    'trilyun': 'triliun',
    'syulit': 'sulit',
    'ikaen': 'ikn',
    'yaelah': 'waduh',
    'maksa': 'memaksa',
    'gpp': 'tidak apa-apa',
    'tau': 'tahu',
    'diih': 'jijik',
    'now': 'sekarang',
    'kebagian': 'mendapat bagian',
    'bree': 'bro',
    'wamen': 'wakil menteri',
    'aja': 'saja',
    'jokodok': 'jokowi',
    'hater': 'pembenci'
    
}
slang_dict_publik.update(kamus_kustom)

In [24]:
def normalisasi_teks(text):
    text = str(text)
    kata_kata = text.split()
    # Mencocokkan dengan kamus yang sudah digabung
    kata_normal = [slang_dict_publik.get(kata, kata) for kata in kata_kata]
    return ' '.join(kata_normal)

In [25]:
df['clean_text'] = df['clean_text'].apply(normalisasi_teks)

In [26]:
sesudah_tahap4 = df.loc[sampel_indeks, 'clean_text'].copy()

In [27]:
tabel_perbandingan_tahap4 = pd.DataFrame({
    'Sebelum': sebelum_tahap4,
    'Sesudah': sesudah_tahap4
})

In [28]:
print("NORMALISASI TEKS")
pd.set_option('display.max_colwidth', None)
display(tabel_perbandingan_tahap4)

NORMALISASI TEKS

,Sebelum,Sesudah
176,faktanya apa ada anggota dpr yang usul jd ibu kota provinsi you cari tau jgn cuma saras soros,faktanya apa ada anggota dpr yang usul jadi ibu kota provinsi you cari tahu jangan cuma saras soros
195,sebenarnya buat siapa kepentingan mega proyek ikn ini belum tentu prabowo dan kabinetnya mau ngantor disana,sebenarnya buat siapa kepentingan mega proyek ikn ini belum tentu prabowo dan kabinetnya mau ngantor disana
815,yg paling bener cuma pak ps di sini parah nih pak mul,yang paling benar cuma pak pas di sini parah nih pak mul
1140,stop ukn project mubazir,stop ukn project mubazir
2615,tobat selama tahun merasakan d pimpin oleh partai banteng segalax serba susah sekarang saatx perubahan,tobat selama tahun merasakan di pimpin oleh partai banteng segalax serba susah sekarang saat perubahan

Memfilter data (hanya bahasa Indonesia, hapus baris kosong, dan duplikat)

In [29]:
print(f"Jumlah baris sebelum difilter: {len(df)}")

Jumlah baris sebelum difilter: 11258

In [30]:
df['clean_text'] = df['clean_text'].replace(r'^\s*$', pd.NA, regex=True)

In [31]:
df = df.dropna(subset=['clean_text'])

In [32]:
df = df.drop_duplicates(subset=['clean_text'], keep='first')

In [33]:
df = df[df['clean_text'].astype(str).str.split().str.len() >= 3]

In [34]:
DetectorFactory.seed = 0

def filter_bahasa_indonesia(text):
    try:
        return detect(str(text)) == 'id'
    except LangDetectException:
        return False

mask_indonesia = df['clean_text'].apply(filter_bahasa_indonesia)

df = df[mask_indonesia].copy()

df = df.reset_index(drop=True)

In [35]:
print(f"Jumlah baris setelah difilter: {len(df)}")

Jumlah baris setelah difilter: 8943

In [ ]:
lokasi_simpan = 'dataset_twitter_clean_final.csv'

df[['clean_text']].to_csv(lokasi_simpan, index=False)

print(f"lokasi: {lokasi_simpan}")

lokasi: dataset_twitter_clean_final.csv